### ISSUE TITLE
Permission not working

### ISSUE THREAD

**Issue by BigAlek** [jolbol1/RandomCoords#1]
I have server Spigot 1.8 from apex hosting site and i use at the moment in the Essentials permissions, i put the sign as on the tutorial and put the permission node "random.sign", in Essentials as i use the other permissions but it works only for op, the default grup cant use it.
All other plugins i used the permissions is ok, just this one i can't get members to use this signs.
Pls help me where i m geting it wrong, i need this bad :(

**Comment by jolbol1** [comment]
Should be working in the most recent update.
