### ISSUE TITLE
Player Buffer Distance

### ISSUE THREAD

**Issue by jhs232** [jolbol1/RandomCoords#2]
If you have time and want to add this, it would be very nice. It basically works like the faction buffer distance - you can't get teleported within X blocks of players. 

Once again, thank you for making and releasing this plugin to the public. I find it amazing that you are willing to spend a lot of time on something that you won't even get paid for.

**Comment by jolbol1** [comment]
PlayerBuffer already exists! 

PlayerBuffer = If true, the random location will have to be the above value away from other players.
PlayerBuffer: true

In the config, Make sure you have the latest.

**Comment by jhs232** [comment]
Sorry about that. I had completely missed it in the config.
