### ISSUE TITLE
Portals direct world

### ISSUE THREAD

**Issue by Atracador** [jolbol1/RandomCoords#4]
Hello, one of your previous features in an old version of the plugin there was an opinion to select the world to randomly teleport to. I am using this feature on my server and for me, without it, there is no use for the plugin, or if there is i would have to adapt (warping and then randomly teleporting). Please, if it is not asking much i would really appreciate if this feature could be readded to the plugin. There is no need to hurry, but i beg you to add it before the update that i am currently using stops working. Thank you for your attention and time. (Sorry for any gramatical mistakes i'm from brazil. :P)

**Comment by jolbol1** [comment]
Im confused, Does /RC portal create {name} {world} not work?

**Comment by Atracador** [comment]
Unless it has been changed from the version before the current one, yes, neither the command or the portal {world} works. Please correct me if i'm mistaken

**Comment by jolbol1** [comment]
I was under the impression it worked in the latest, and the feature has never been removed. Im working on the code later so will check and run some tests.

**Comment by jolbol1** [comment]
Did some testing in v6.1.0 Portals to other worlds work. /Rc will always tp you to the world that your in, Signs will teleport you to the world specified on the second line.

**Comment by Atracador** [comment]
Thank you so much
